### ISSUE TITLE
RuntimeError: Boolean value of Tensor with more than one value is ambiguous

### ISSUE THREAD

**Issue by quanhoang288** [castorini/DeeBERT#8]
Hi there I was using your model for my new classification task on Japanese text so I added the configuration needed for Japanese Bert
I'm doing the training on the BertForSequenceClassifcation model and when I do validation I encountered a bug that said the if condition was done on a tensor with more than one value (that tensor is actually the highway entropy of a batch) so that threw a runtime error when compared with the early exit threshold
Can you help me with this ? I'd appreciate your help on this problem 
Here is the snippet of the error code 
![image](https://user-images.githubusercontent.com/47912719/111302736-55505600-8686-11eb-86a2-11a360c91e4f.png)

**Comment by Ji-Xin** [comment]
Hi, sorry for the late reply. I guess you are doing inference with a batch_size greater than 1? In our implementation the inference batch_size can only be 1, and the reason is exactly the issue you descirbed.

**Comment by JulesBelveze** [comment]
Hey @ji-xin I'm facing the same problem than @quanhoang288.
Any idea how what could be a relevant way to adapt it to handle batches with size greater than 1?

**Comment by ji-xin** [comment]
I'm afraid there isn't a straightforward way to do it. It's certainly possible: given a layer, feed in a batch of examples, perform early exiting on each of them individually, and regroup the low-confidence examples into a new batch that will be fed to the next layer. However, this will require a bit of engineering efforts.
